"""
WAF Fingerprinting Engine
==========================
Passively identifies Web Application Firewalls through response analysis.
Builds a signature from headers, cookies, and error pages to determine
which WAF technology is protecting the target.

This enables targeted mutation generation — different WAFs have
different known bypass techniques.
"""

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

import structlog
from wafmancer.core.http_client import ResearchResponse

logger = structlog.get_logger(__name__)


class WAFVendor(Enum):
    """Known WAF vendors with their characteristics."""
    CLOUDFLARE = "Cloudflare"
    AWS_WAF = "AWS WAF"
    AKAMAI = "Akamai Kona"
    IMPERVA = "Imperva/Incapsula"
    F5_BIGIP = "F5 BIG-IP ASM"
    FORTINET = "Fortinet FortiWeb"
    MODSECURITY = "ModSecurity (Generic)"
    SUCURI = "Sucuri WAF"
    BARRACUDA = "Barracuda WAF"
    CITRIX = "Citrix NetScaler"
    RADWARE = "Radware AppWall"
    UNKNOWN = "Unknown WAF"
    NONE = "No WAF Detected"


@dataclass
class WAFSignature:
    """Complete fingerprint of a detected WAF."""
    vendor: WAFVendor
    confidence: float  # 0.0 to 1.0
    evidence: List[str] = field(default_factory=list)
    headers_found: Dict[str, str] = field(default_factory=dict)
    cookies_found: Dict[str, str] = field(default_factory=dict)
    block_page_hash: str = ""
    known_vulnerabilities: List[str] = field(default_factory=list)
    suggested_mutations: List[str] = field(default_factory=list)


class WAFFingerprinter:
    """
    Passive WAF detection through multi-vector signature analysis.
    
    Detection methods:
    1. HTTP Header analysis (Server, X-* headers)
    2. Cookie analysis (session cookies with WAF patterns)
    3. Response body patterns (block pages, error templates)
    4. Behavioral analysis (how it handles malformed requests)
    """

    # WAF Signature Database — headers that uniquely identify WAFs
    HEADER_SIGNATURES: Dict[str, Tuple[WAFVendor, float]] = {
        # Cloudflare
        "cf-ray": (WAFVendor.CLOUDFLARE, 1.0),
        "cf-cache-status": (WAFVendor.CLOUDFLARE, 0.9),
        "__cf_bm": (WAFVendor.CLOUDFLARE, 0.8),
        
        # AWS WAF
        "x-amzn-requestid": (WAFVendor.AWS_WAF, 0.7),
        "x-amz-cf-id": (WAFVendor.AWS_WAF, 0.7),
        "x-amz-cf-pop": (WAFVendor.AWS_WAF, 0.7),
        
        # Akamai
        "x-akamai-transformed": (WAFVendor.AKAMAI, 1.0),
        "x-akamai-request-id": (WAFVendor.AKAMAI, 0.9),
        
        # Imperva/Incapsula
        "x-iinfo": (WAFVendor.IMPERVA, 1.0),
        "x-cdn": (WAFVendor.IMPERVA, 0.8),
        
        # F5 BIG-IP
        "x-wa-info": (WAFVendor.F5_BIGIP, 1.0),
        "x-cnection": (WAFVendor.F5_BIGIP, 0.9),
        
        # Fortinet
        "x-fortigate": (WAFVendor.FORTINET, 1.0),
        
        # ModSecurity
        "x-modsecurity": (WAFVendor.MODSECURITY, 1.0),
        
        # Sucuri
        "x-sucuri-id": (WAFVendor.SUCURI, 1.0),
        "x-sucuri-cache": (WAFVendor.SUCURI, 0.9),
        
        # Barracuda
        "x-barracuda": (WAFVendor.BARRACUDA, 1.0),
        
        # Citrix NetScaler
        "x-ns-proxy": (WAFVendor.CITRIX, 1.0),
        "x-ns-management": (WAFVendor.CITRIX, 0.9),
    }

    # Cookie patterns that indicate specific WAFs
    COOKIE_SIGNATURES: Dict[str, Tuple[WAFVendor, float]] = {
        "__cfduid": (WAFVendor.CLOUDFLARE, 0.9),
        "cf_clearance": (WAFVendor.CLOUDFLARE, 0.9),
        "aws-waf-token": (WAFVendor.AWS_WAF, 1.0),
        "ak_bmsc": (WAFVendor.AKAMAI, 1.0),
        "bm_sz": (WAFVendor.AKAMAI, 0.9),
        "incap_ses_": (WAFVendor.IMPERVA, 1.0),
        "visid_incap_": (WAFVendor.IMPERVA, 0.9),
        "BNI__BARRACUDA_": (WAFVendor.BARRACUDA, 1.0),
        "citrix_ns_id": (WAFVendor.CITRIX, 1.0),
    }

    # Response body patterns for block page detection
    BLOCK_PAGE_PATTERNS: Dict[str, Tuple[WAFVendor, float]] = {
        "Cloudflare Ray ID:": (WAFVendor.CLOUDFLARE, 1.0),
        "Attention Required! | Cloudflare": (WAFVendor.CLOUDFLARE, 1.0),
        "Generated by cloudfront": (WAFVendor.AWS_WAF, 0.8),
        "Request blocked.": (WAFVendor.AWS_WAF, 0.6),
        "Access Denied: Akamai": (WAFVendor.AKAMAI, 1.0),
        "The requested URL was rejected": (WAFVendor.F5_BIGIP, 0.9),
        "ModSecurity": (WAFVendor.MODSECURITY, 1.0),
        "This error page was generated by ModSecurity": (WAFVendor.MODSECURITY, 1.0),
        "Sucuri WebSite Firewall": (WAFVendor.SUCURI, 1.0),
        "Access Denied - Sucuri": (WAFVendor.SUCURI, 1.0),
        "Barracuda Networks": (WAFVendor.BARRACUDA, 1.0),
        "FortiWeb - Web Application Firewall": (WAFVendor.FORTINET, 1.0),
        "Incapsula incident": (WAFVendor.IMPERVA, 1.0),
    }

    # Known bypass techniques per WAF
    WAF_BYPASS_KNOWLEDGE: Dict[WAFVendor, List[str]] = {
        WAFVendor.CLOUDFLARE: [
            "HTTP/2 multiplexing bypass",
            "WebSocket upgrade smuggling",
            "Cache deception via extension manipulation",
            "Origin IP exposure via DNS history",
        ],
        WAFVendor.AWS_WAF: [
            "X-Forwarded-For header injection",
            "Request size limit bypass",
            "JSON body parsing inconsistency",
            "Lambda@Edge timeout exploitation",
        ],
        WAFVendor.AKAMAI: [
            "Header transformation bypass",
            "URL normalization difference",
            "Request smuggling CL/TE",
        ],
        WAFVendor.IMPERVA: [
            "Double URL encoding bypass",
            "Multipart boundary injection",
            "Parameter pollution",
        ],
        WAFVendor.MODSECURITY: [
            "Regex ReDoS exploitation",
            "Unicode normalization bypass",
            "HTTP Parameter Pollution (HPP)",
            "Null byte injection",
        ],
        WAFVendor.F5_BIGIP: [
            "ASM bypass via cookie manipulation",
            "XML External Entity (XXE) bypass",
            "Header folding technique",
        ],
    }

    def __init__(self) -> None:
        """Initialize the WAF fingerprinter."""
        logger.info("waf_fingerprinter_initialized")

    async def fingerprint(
        self,
        baseline_response: ResearchResponse,
        probe_response: Optional[ResearchResponse] = None,
    ) -> WAFSignature:
        """
        Fingerprint the WAF protecting a target.

        Args:
            baseline_response: Clean baseline response
            probe_response: Optional response from a probe that triggered a block

        Returns:
            Complete WAFSignature with vendor identification and confidence
        """
        evidence: List[str] = []
        vendor_scores: Dict[WAFVendor, float] = {}
        headers_found: Dict[str, str] = {}
        cookies_found: Dict[str, str] = {}

        # Method 1: Header Analysis
        for header_name, (vendor, confidence) in self.HEADER_SIGNATURES.items():
            for resp_header, resp_value in baseline_response.headers.items():
                if resp_header.lower() == header_name.lower():
                    headers_found[resp_header] = str(resp_value)
                    vendor_scores[vendor] = vendor_scores.get(vendor, 0) + confidence
                    evidence.append(
                        f"Header '{resp_header}' matches {vendor.value} signature "
                        f"(confidence: {confidence})"
                    )

        # Method 2: Cookie Analysis
        if "set-cookie" in baseline_response.headers:
            cookie_header = str(baseline_response.headers["set-cookie"])
            for cookie_name, (vendor, confidence) in self.COOKIE_SIGNATURES.items():
                if cookie_name.lower() in cookie_header.lower():
                    cookies_found[cookie_name] = cookie_header
                    vendor_scores[vendor] = vendor_scores.get(vendor, 0) + confidence
                    evidence.append(
                        f"Cookie '{cookie_name}' indicates {vendor.value} "
                        f"(confidence: {confidence})"
                    )

        # Method 3: Server Header Analysis
        server_header = baseline_response.server_header.lower()
        if "cloudflare" in server_header:
            vendor_scores[WAFVendor.CLOUDFLARE] = vendor_scores.get(WAFVendor.CLOUDFLARE, 0) + 0.8
            evidence.append(f"Server header contains 'cloudflare'")
        elif "akamai" in server_header:
            vendor_scores[WAFVendor.AKAMAI] = vendor_scores.get(WAFVendor.AKAMAI, 0) + 0.8
            evidence.append(f"Server header contains 'akamai'")
        elif "bigip" in server_header:
            vendor_scores[WAFVendor.F5_BIGIP] = vendor_scores.get(WAFVendor.F5_BIGIP, 0) + 0.8
            evidence.append(f"Server header contains 'bigip'")

        # Method 4: Block Page Analysis (if probe triggered a block)
        block_page_hash = ""
        if probe_response and probe_response.status_code == 403:
            for pattern, (vendor, confidence) in self.BLOCK_PAGE_PATTERNS.items():
                if pattern.lower() in probe_response.body_text.lower():
                    vendor_scores[vendor] = vendor_scores.get(vendor, 0) + confidence
                    evidence.append(
                        f"Block page matches {vendor.value} pattern"
                    )
                    import hashlib
                    block_page_hash = hashlib.md5(probe_response.body).hexdigest()

        # Determine final vendor and confidence
        if not vendor_scores:
            return WAFSignature(
                vendor=WAFVendor.NONE,
                confidence=0.0,
                evidence=["No WAF signatures detected"],
            )

        # Weighted scoring
        best_vendor = max(vendor_scores, key=vendor_scores.get)
        best_score = vendor_scores[best_vendor]
        
        # Normalize confidence (max reasonable score is ~4.0)
        confidence = min(best_score / 4.0, 1.0)

        # Get known bypasses for this WAF
        known_vulns = self.WAF_BYPASS_KNOWLEDGE.get(best_vendor, [])
        suggested_mutations = self._generate_waf_specific_mutations(best_vendor)

        signature = WAFSignature(
            vendor=best_vendor,
            confidence=confidence,
            evidence=evidence,
            headers_found=headers_found,
            cookies_found=cookies_found,
            block_page_hash=block_page_hash,
            known_vulnerabilities=known_vulns,
            suggested_mutations=suggested_mutations,
        )

        logger.info(
            "waf_fingerprinted",
            vendor=best_vendor.value,
            confidence=f"{confidence:.1%}",
            evidence_count=len(evidence),
        )

        return signature

    def _generate_waf_specific_mutations(self, vendor: WAFVendor) -> List[str]:
        """
        Generate WAF-specific mutation suggestions based on known bypasses.

        Args:
            vendor: The identified WAF vendor

        Returns:
            List of suggested mutation techniques
        """
        mutation_map = {
            WAFVendor.CLOUDFLARE: [
                "HTTP/2 connection coalescing test",
                "Cache deception via .css extension",
                "WebSocket upgrade header injection",
            ],
            WAFVendor.AWS_WAF: [
                "X-Forwarded-For chain injection (multiple IPs)",
                "Oversized request body test",
                "JSON with duplicate keys",
            ],
            WAFVendor.AKAMAI: [
                "Hop-by-hop header injection",
                "Absolute URI in request line",
                "Chunked transfer encoding variant",
            ],
            WAFVendor.IMPERVA: [
                "Double URL encoding bypass",
                "Unicode homoglyph injection",
                "HTTP Parameter Pollution (HPP)",
            ],
            WAFVendor.MODSECURITY: [
                "Regex timeout probe (ReDoS detection)",
                "Null byte in parameter name",
                "Path normalization bypass",
                "PHP wrapper injection",
            ],
            WAFVendor.F5_BIGIP: [
                "ASM cookie spoofing",
                "HTTP Request Smuggling (CL.TE)",
                "Header folding attack",
            ],
        }

        return mutation_map.get(vendor, [
            "Generic header injection test",
            "Content-Type manipulation",
            "Request body parsing test",
        ])

    def generate_fingerprint_report(self, signature: WAFSignature) -> str:
        """
        Generate a human-readable fingerprint report.

        Args:
            signature: The WAF fingerprint

        Returns:
            Markdown-formatted report
        """
        lines = [
            "=" * 60,
            "WAFMANCER — WAF Fingerprint Report",
            "=" * 60,
            f"Vendor:     {signature.vendor.value}",
            f"Confidence: {signature.confidence:.1%}",
            "",
            "--- Evidence ---",
        ]

        for e in signature.evidence:
            lines.append(f"  ✓ {e}")

        if signature.known_vulnerabilities:
            lines.append("")
            lines.append("--- Known Bypass Vectors ---")
            for v in signature.known_vulnerabilities:
                lines.append(f"  ⚡ {v}")

        if signature.suggested_mutations:
            lines.append("")
            lines.append("--- Suggested Mutations ---")
            for m in signature.suggested_mutations:
                lines.append(f"  🧬 {m}")

        lines.append("=" * 60)
        return "\n".join(lines)
